blank_issues_enabled: true
contact_links:
  - name: A User's Guide to Getting Help
    url:
    about: A resource which describes all the steps you should go through when
    you're facing an issue with this library.
