# This workflow will do a clean install of node dependencies, run JS and Typescript tests.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docs

on: [push, pull_request]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Install Inkscape
      run: |
        sudo apt-get -y install inkscape
        inkscape --version
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --immutable
    - run: yarn workspace react-native-render-html build
      name: Build sources
    - run: yarn process-svg-assets
      name: Process SVG assets
    - run: yarn build:tools
      name: Build Tooling Libraries
    - run: yarn build:docs
      name: Build documentation
    - run: yarn website build
      name: Build website