name: Npm
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'NPM exact version'
        required: true
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]
    
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install React Native CLI
        run: npm install -g @react-native-community/cli
      - name: Init new project
        run: react-native init --npm test; cd test
      - name: Install @next
        run: "npm install react-native-render-html@${{ github.event.inputs.version }}"